name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
        ghc_version:
          - "9.2.8"
          - "9.4.8"
          - "9.6.6"
          - "9.8.4"
          - "9.10.3"
          - "9.12.2"
      fail-fast: false
    name: Build on Linux, GHC ${{ matrix.ghc_version }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc_version }}
          cabal-version: "3.16.0.0"
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-stack-${{ matrix.ghc_version }}
      - name: cabal configure
        run: cabal configure --with-ghc=ghc-${{ matrix.ghc_version }}
      - name: Install dependencies
        run: cabal build --dependencies-only --enable-tests --haddock-all
      - name: cabal build
        run: cabal build --ghc-options=-Werror
      - run: cabal check
      - run: cabal haddock
