name: Release

on:
  release:
    types:
      - prereleased

permissions:
  contents: write

jobs:
  sdist:
    runs-on: ubuntu-latest
    name: Build source tarball
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          cabal-version: "3.16.0.0"
      - name: cabal sdist
        run: |
          cabal sdist --output-dir "$GITHUB_WORKSPACE/sdist"
          echo "dist=$(find "$GITHUB_WORKSPACE/sdist" -maxdepth 1 -type f -name '*.tar.gz')" >> "$GITHUB_ENV"
      - uses: actions/upload-artifact@v4
        with:
          name: Source tarball
          path: ${{ env.dist }}
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.dist }}
          tag: ${{ github.ref }}
      - name: Upload tarball to hackage
        run: |
          curl -X POST 'https://hackage.haskell.org/packages/candidates/' -H "Authorization: X-ApiKey ${{ secrets.HACKAGE_KEY }}" -F "package=@$dist" -w '%{url_effective}\n'
